# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tqdecoration.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tqdecoration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12tqdecoration.proto\x12\x0ctqdecoration\"*\n\x07ReqInfo\x12\x0e\n\x06userid\x18\x01 \x02(\x05\x12\x0f\n\x07usersex\x18\x02 \x01(\x05\"\xb2\x01\n\x07RspInfo\x12\x0e\n\x06status\x18\x01 \x02(\x05\x12-\n\x0b\x64\x65\x63orations\x18\x02 \x03(\x0b\x32\x18.tqdecoration.Decoration\x12\x38\n\x10\x64\x65\x63orationrecord\x18\x03 \x01(\x0b\x32\x1e.tqdecoration.DecorationRecord\x12.\n\x0b\x64\x65\x66\x61ultInfo\x18\x04 \x01(\x0b\x32\x19.tqdecoration.DefaultInfo\"\x1f\n\rNtfRobotEnter\x12\x0e\n\x06userid\x18\x01 \x02(\x05\"l\n\x0b\x44\x65\x66\x61ultInfo\x12\x16\n\x0e\x64\x65\x66\x61ultheadid1\x18\x01 \x01(\x05\x12\x16\n\x0e\x64\x65\x66\x61ultheadid2\x18\x02 \x01(\x05\x12\x16\n\x0e\x64\x65\x66\x61ulttableid\x18\x03 \x01(\x05\x12\x15\n\rdefaultcardid\x18\x04 \x01(\x05\"U\n\x13ReqDecorationUpdate\x12\x0e\n\x06userid\x18\x01 \x02(\x05\x12.\n\x06record\x18\x02 \x02(\x0b\x32\x1e.tqdecoration.DecorationRecord\"n\n\nDecoration\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0e\n\x06propid\x18\x02 \x01(\x05\x12\r\n\x05isnew\x18\x03 \x01(\x05\x12\x10\n\x08resindex\x18\x04 \x01(\x05\x12\x15\n\rrelatedmodule\x18\x05 \x01(\x0c\x12\x0c\n\x04type\x18\x06 \x01(\x05\"G\n\x10\x44\x65\x63orationRecord\x12\x0e\n\x06headid\x18\x01 \x01(\x05\x12\x0f\n\x07tableid\x18\x02 \x01(\x05\x12\x12\n\ncardtypeid\x18\x03 \x01(\x05\"A\n\x0f\x44\x65\x63orationCache\x12.\n\x06record\x18\x01 \x02(\x0b\x32\x1e.tqdecoration.DecorationRecord')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tqdecoration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQINFO']._serialized_start=36
  _globals['_REQINFO']._serialized_end=78
  _globals['_RSPINFO']._serialized_start=81
  _globals['_RSPINFO']._serialized_end=259
  _globals['_NTFROBOTENTER']._serialized_start=261
  _globals['_NTFROBOTENTER']._serialized_end=292
  _globals['_DEFAULTINFO']._serialized_start=294
  _globals['_DEFAULTINFO']._serialized_end=402
  _globals['_REQDECORATIONUPDATE']._serialized_start=404
  _globals['_REQDECORATIONUPDATE']._serialized_end=489
  _globals['_DECORATION']._serialized_start=491
  _globals['_DECORATION']._serialized_end=601
  _globals['_DECORATIONRECORD']._serialized_start=603
  _globals['_DECORATIONRECORD']._serialized_end=674
  _globals['_DECORATIONCACHE']._serialized_start=676
  _globals['_DECORATIONCACHE']._serialized_end=741
# @@protoc_insertion_point(module_scope)
