# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tqvip.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tqvip.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btqvip.proto\x12\x06xzmpDB\"\xb4\x01\n\x10TQVip_PlayerData\x12\x12\n\nexperience\x18\x01 \x01(\x05\x12\r\n\x05grade\x18\x02 \x01(\x05\x12\x15\n\rmaxexperience\x18\x03 \x01(\x05\x12\x10\n\x08maxgrade\x18\x04 \x01(\x05\x12\x14\n\x0crewardstatus\x18\x05 \x03(\x05\x12\x0f\n\x07\x64\x61tetag\x18\x06 \x01(\x05\x12\x18\n\x10lastshowanigrade\x18\x07 \x01(\x05\x12\x13\n\x0bisdemoteani\x18\x08 \x01(\x05\"?\n\x11TQMonthCard_Cache\x12*\n\x06player\x18\x01 \x01(\x0b\x32\x1a.xzmpDB.TQMonthCard_Player\"\x81\x01\n\x12TQMonthCard_Player\x12\x35\n\tmonthcard\x18\x01 \x01(\x0b\x32\".xzmpDB.TQMonthCard_PlayerCardInfo\x12\x34\n\x08weekcard\x18\x02 \x01(\x0b\x32\".xzmpDB.TQMonthCard_PlayerCardInfo\"Q\n\x1aTQMonthCard_PlayerCardInfo\x12\x0f\n\x07\x64\x61tetag\x18\x01 \x01(\x05\x12\x11\n\tstarttime\x18\x02 \x01(\x03\x12\x0f\n\x07\x65ndtime\x18\x03 \x01(\x03\")\n\nPropsCache\x12\x1b\n\x05items\x18\x01 \x03(\x0b\x32\x0c.xzmpDB.Item\"j\n\x04Item\x12\x0e\n\x06propid\x18\x01 \x03(\x05\x12&\n\ncommoninfo\x18\x02 \x01(\x0b\x32\x12.xzmpDB.CommonInfo\x12*\n\x0c\x62\x61opeikainfo\x18\x03 \x01(\x0b\x32\x14.xzmpDB.BaoPeiKaInfo\"Y\n\nCommonInfo\x12\'\n\x0bnumberitems\x18\x01 \x03(\x0b\x32\x12.xzmpDB.NumberItem\x12\"\n\x08timeitem\x18\x02 \x01(\x0b\x32\x10.xzmpDB.TimeItem\"R\n\x0c\x42\x61oPeiKaInfo\x12\x0f\n\x07gettime\x18\x01 \x01(\x03\x12\x0f\n\x07\x65ndtime\x18\x02 \x01(\x03\x12\x0f\n\x07\x64\x61tetag\x18\x03 \x01(\x05\x12\x0f\n\x07opcount\x18\x04 \x01(\x03\",\n\nNumberItem\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\x12\x0f\n\x07gettime\x18\x02 \x01(\x03\"/\n\x08TimeItem\x12\x12\n\nexpiredate\x18\x01 \x01(\x03\x12\x0f\n\x07gettime\x18\x02 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tqvip_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TQVIP_PLAYERDATA']._serialized_start=24
  _globals['_TQVIP_PLAYERDATA']._serialized_end=204
  _globals['_TQMONTHCARD_CACHE']._serialized_start=206
  _globals['_TQMONTHCARD_CACHE']._serialized_end=269
  _globals['_TQMONTHCARD_PLAYER']._serialized_start=272
  _globals['_TQMONTHCARD_PLAYER']._serialized_end=401
  _globals['_TQMONTHCARD_PLAYERCARDINFO']._serialized_start=403
  _globals['_TQMONTHCARD_PLAYERCARDINFO']._serialized_end=484
  _globals['_PROPSCACHE']._serialized_start=486
  _globals['_PROPSCACHE']._serialized_end=527
  _globals['_ITEM']._serialized_start=529
  _globals['_ITEM']._serialized_end=635
  _globals['_COMMONINFO']._serialized_start=637
  _globals['_COMMONINFO']._serialized_end=726
  _globals['_BAOPEIKAINFO']._serialized_start=728
  _globals['_BAOPEIKAINFO']._serialized_end=810
  _globals['_NUMBERITEM']._serialized_start=812
  _globals['_NUMBERITEM']._serialized_end=856
  _globals['_TIMEITEM']._serialized_start=858
  _globals['_TIMEITEM']._serialized_end=905
# @@protoc_insertion_point(module_scope)
